<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Adverts extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Adverts_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'adverts/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'adverts/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'adverts/index.html';
            $config['first_url'] = base_url() . 'adverts/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Adverts_model->total_rows($q);
        $adverts = $this->Adverts_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'adverts_data' => $adverts,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('adverts/adverts_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Adverts_model->get_by_id($id);
        if ($row) {
            $data = array(
		'adverts_id' => $row->adverts_id,
		'adverts_name' => $row->adverts_name,
		'stores_id' => $row->stores_id,
	    );
            $this->load->view('adverts/adverts_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adverts'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('adverts/create_action'),
	    'adverts_id' => set_value('adverts_id'),
	    'adverts_name' => set_value('adverts_name'),
	    'stores_id' => set_value('stores_id'),
	);
        $this->load->view('adverts/adverts_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'adverts_name' => $this->input->post('adverts_name',TRUE),
		'stores_id' => $this->input->post('stores_id',TRUE),
	    );

            $this->Adverts_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('adverts'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Adverts_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('adverts/update_action'),
		'adverts_id' => set_value('adverts_id', $row->adverts_id),
		'adverts_name' => set_value('adverts_name', $row->adverts_name),
		'stores_id' => set_value('stores_id', $row->stores_id),
	    );
            $this->load->view('adverts/adverts_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adverts'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('adverts_id', TRUE));
        } else {
            $data = array(
		'adverts_name' => $this->input->post('adverts_name',TRUE),
		'stores_id' => $this->input->post('stores_id',TRUE),
	    );

            $this->Adverts_model->update($this->input->post('adverts_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('adverts'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Adverts_model->get_by_id($id);

        if ($row) {
            $this->Adverts_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('adverts'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adverts'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('adverts_name', 'adverts name', 'trim|required');
	$this->form_validation->set_rules('stores_id', 'stores id', 'trim|required');

	$this->form_validation->set_rules('adverts_id', 'adverts_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Adverts.php */
/* Location: ./application/controllers/Adverts.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-10 16:37:33 */
/* http://harviacode.com */