<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Books extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Books_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('books/books_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Books_model->json();
    }

    public function read($id) 
    {
        $row = $this->Books_model->get_by_id($id);
        if ($row) {
            $data = array(
		'books_id' => $row->books_id,
		'title' => $row->title,
		'Release_date' => $row->Release_date,
	    );
            $this->load->view('books/books_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('books'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('books/create_action'),
	    'books_id' => set_value('books_id'),
	    'title' => set_value('title'),
	    'Release_date' => set_value('Release_date'),
	);
        $this->load->view('books/books_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'books_id' => $this->input->post('books_id',TRUE),
		'title' => $this->input->post('title',TRUE),
		'Release_date' => $this->input->post('Release_date',TRUE),
	    );

            $this->Books_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('books'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Books_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('books/update_action'),
		'books_id' => set_value('books_id', $row->books_id),
		'title' => set_value('title', $row->title),
		'Release_date' => set_value('Release_date', $row->Release_date),
	    );
            $this->load->view('books/books_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('books'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'books_id' => $this->input->post('books_id',TRUE),
		'title' => $this->input->post('title',TRUE),
		'Release_date' => $this->input->post('Release_date',TRUE),
	    );

            $this->Books_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('books'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Books_model->get_by_id($id);

        if ($row) {
            $this->Books_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('books'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('books'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('books_id', 'books id', 'trim|required');
	$this->form_validation->set_rules('title', 'title', 'trim|required');
	$this->form_validation->set_rules('Release_date', 'release date', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Books.php */
/* Location: ./application/controllers/Books.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-10 15:19:35 */
/* http://harviacode.com */