<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Booklist_model extends CI_Model
{

    public $table = 'booklist';
    public $id = 'booklist_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_kode(){
        $this->db->select('RIGHT(books.books_id,4) as kode', FALSE);
        $this->db->order_by('books_id','DESC');    
        $this->db->limit(1);
          $query = $this->db->get('books');      //cek dulu apakah ada sudah ada kode di tabel.    
          if($query->num_rows() <> 0){      
           //jika kode ternyata sudah ada.      
           $data = $query->row();      
           $kode = intval($data->kode) + 1;    
          }
          else {      
           //jika kode belum ada      
           $kode = 1;    
          }
          $kodemax = str_pad($kode, 4, "0", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
          $d = date('Ymd');
          $kodejadi = "book-".$d.'-'.$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;  
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_books_id($id)
    {
        $this->db->where('books_id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('booklist_id', $q);
	$this->db->or_like('stores_id', $q);
	$this->db->or_like('books_id', $q);
	$this->db->or_like('book_stock', $q);
	$this->db->or_like('price', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('booklist_id', $q);
	$this->db->or_like('stores_id', $q);
	$this->db->or_like('books_id', $q);
	$this->db->or_like('book_stock', $q);
	$this->db->or_like('price', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_b($data)
    {
        $this->db->insert_batch($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Booklist_model.php */
/* Location: ./application/models/Booklist_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-10 16:37:35 */
/* http://harviacode.com */