<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Owners_model extends CI_Model
{

    public $table = 'owners';
    public $id = 'owners_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('stores', 'owners.stores_id=stores.stores_id');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_code($code)
    {
        $this->db->where('code', $code);
        return $this->db->get($this->table)->row();
    }
    
    function register($id)
    {
        $this->db->set('is_verify', '1');
        $this->db->set('reg_time', 'NOW()', false);
        $this->db->where($this->id, $id);
        $this->db->update($this->table);
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('owners_id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('birth_date', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('is_verify', $q);
	$this->db->or_like('stores_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('owners_id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('birth_date', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('is_verify', $q);
	$this->db->or_like('stores_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Owners_model.php */
/* Location: ./application/models/Owners_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-02 14:35:38 */
/* http://harviacode.com */