<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Stores_model extends CI_Model
{

    public $table = 'stores';
    public $id = 'stores_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('stores_id,store_name,description,address,lat,lang,open,contact,owners_id');
        $this->datatables->from('stores');
        //add this line for join
        //$this->datatables->join('table2', 'stores.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('stores/read/$1'),'Read')." | ".anchor(site_url('stores/update/$1'),'Update')." | ".anchor(site_url('stores/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'stores_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('stores_id', $q);
	$this->db->or_like('store_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lang', $q);
	$this->db->or_like('open', $q);
	$this->db->or_like('contact', $q);
	$this->db->or_like('owners_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('stores_id', $q);
	$this->db->or_like('store_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lang', $q);
	$this->db->or_like('open', $q);
	$this->db->or_like('contact', $q);
	$this->db->or_like('owners_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Stores_model.php */
/* Location: ./application/models/Stores_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-10 15:19:37 */
/* http://harviacode.com */